Week 2 paul gooden
learn-academy-2023-delta/week-2-assessment-Phalco1 pull request #1
Opened 2023-05-24 00:12 UTC by Phalco1

# Submitting Week 2 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [ ] Coding Challenges
- [ X] Coding Concepts
- [ X] Interview Questions

### ✋ Reminder

Do NOT merge your assessment!

### 📝 Feedback

If you would like specific feedback please leave details here:

I didn't do the last question on the coding challenges due to my wife being sick and I have 3 children. Plus I had 2 VA appointments that drew my attention away so I had to make up with studying. But I did the best I could and I think that should be the only unanswered question in the assessment beside the stretch questions.

2023-05-25 17:46 UTC, chrisyhlee requested changes
Hey Paul, I saw your note about challenge 3, hope everything is okay now! I can't approve this PR until there is a valid attempt, so once you complete challenge 3, you can add, commit, and push up to the same branch.

2023-05-25 17:46 UTC, chrisyhlee commented on code-challenges.test.js
> +//         expect(divideBy3(object3.number)).toEqual("-7 is not divisible by three")
The prompt tells you that your function should take an object as an argument, not the number in that object.

2023-05-25 17:46 UTC, chrisyhlee commented on code-challenges.test.js
> +//  4.) Add the .join('') with single quotations to join the string "letters" back to string "words".
Good logic here!

2023-05-25 17:48 UTC, Phalco1 commented
I’ll do it asap

On Thu, May 25, 2023 at 12:46 Chris ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey Paul, I saw your note about challenge 3, hope everything is okay now!
> I can't approve this PR until there is a valid attempt, so once you
> complete challenge 3, you can add, commit, and push up to the same branch.
> ------------------------------
>
> In code-challenges.test.js
> <https://github.com/learn-academy-2023-delta/week-2-assessment-Phalco1/pull/1#discussion_r1205695348>
> :
>
> > +
> +// // //  1.) Write a describe statement to take in the argument of a string and function.
> +
> +// // // 2.) Write an it statement in the describe block as a string describing what the test is doing with a function (anonymous function)
> +
> +// // // 3.) Write 3 expect statement to take in the each encased function call with the .toEqual() method with the strings encased in the .toEqual method.
> +
> +// // // 4.) Create a function with a conditional statement if the object is divisible by 3 then itll return that number is divisible by 3. if else, itll return the number is not divisible by 3.
> +
> +// // // 1.) CREATE
> +
> +// describe("divideBy3", () => {
> +//     it("decides if the number inside is divisible by 3.", () => {
> +//         expect(divideBy3(object1.number)).toEqual("15 is divisible by three")
> +//         expect(divideBy3(object2.number)).toEqual("0 is divisible by three")
> +//         expect(divideBy3(object3.number)).toEqual("-7 is not divisible by three")
>
> The prompt tells you that your function should take an object as an
> argument, not the number in that object.
> ------------------------------
>
> In code-challenges.test.js
> <https://github.com/learn-academy-2023-delta/week-2-assessment-Phalco1/pull/1#discussion_r1205836709>
> :
>
> >
> -// Pseudo code:
> +// // Pseudo code:
> +
> +//  1.) Write a function that take in the array and add the map HOF to iterate in the array.
> +
> +//  2.) In the map HOF write a function that takes the value you are iterating and split the strings into individual strings of letters.
> +
> +//  3.) add another map HOF to iterate each individual letter and add a conditional statement to return the 0 index in the string uppercased and the rest of the string as is.
> +
> +//  4.) Add the .join('') with single quotations to join the string "letters" back to string "words".
>
> Good logic here!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/learn-academy-2023-delta/week-2-assessment-Phalco1/pull/1#pullrequestreview-1444170331>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A65Q3ZC4DTXLZ7TV7EDMEHLXH6LIRANCNFSM6AAAAAAYMSXVZM>
> .
> You are receiving this because you authored the thread.Message ID:
> <learn-academy-2023-delta/week-2-assessment-Phalco1/pull/1/review/1444170331
> @github.com>
>

2023-05-25 17:48 UTC, Phalco1 commented
I’ll do it during lunch

On Thu, May 25, 2023 at 12:47 Paul Gooden ***@***.***> wrote:

> I’ll do it asap
>
> On Thu, May 25, 2023 at 12:46 Chris ***@***.***> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Hey Paul, I saw your note about challenge 3, hope everything is okay now!
>> I can't approve this PR until there is a valid attempt, so once you
>> complete challenge 3, you can add, commit, and push up to the same branch.
>> ------------------------------
>>
>> In code-challenges.test.js
>> <https://github.com/learn-academy-2023-delta/week-2-assessment-Phalco1/pull/1#discussion_r1205695348>
>> :
>>
>> > +
>> +// // //  1.) Write a describe statement to take in the argument of a string and function.
>> +
>> +// // // 2.) Write an it statement in the describe block as a string describing what the test is doing with a function (anonymous function)
>> +
>> +// // // 3.) Write 3 expect statement to take in the each encased function call with the .toEqual() method with the strings encased in the .toEqual method.
>> +
>> +// // // 4.) Create a function with a conditional statement if the object is divisible by 3 then itll return that number is divisible by 3. if else, itll return the number is not divisible by 3.
>> +
>> +// // // 1.) CREATE
>> +
>> +// describe("divideBy3", () => {
>> +//     it("decides if the number inside is divisible by 3.", () => {
>> +//         expect(divideBy3(object1.number)).toEqual("15 is divisible by three")
>> +//         expect(divideBy3(object2.number)).toEqual("0 is divisible by three")
>> +//         expect(divideBy3(object3.number)).toEqual("-7 is not divisible by three")
>>
>> The prompt tells you that your function should take an object as an
>> argument, not the number in that object.
>> ------------------------------
>>
>> In code-challenges.test.js
>> <https://github.com/learn-academy-2023-delta/week-2-assessment-Phalco1/pull/1#discussion_r1205836709>
>> :
>>
>> >
>> -// Pseudo code:
>> +// // Pseudo code:
>> +
>> +//  1.) Write a function that take in the array and add the map HOF to iterate in the array.
>> +
>> +//  2.) In the map HOF write a function that takes the value you are iterating and split the strings into individual strings of letters.
>> +
>> +//  3.) add another map HOF to iterate each individual letter and add a conditional statement to return the 0 index in the string uppercased and the rest of the string as is.
>> +
>> +//  4.) Add the .join('') with single quotations to join the string "letters" back to string "words".
>>
>> Good logic here!
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/learn-academy-2023-delta/week-2-assessment-Phalco1/pull/1#pullrequestreview-1444170331>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A65Q3ZC4DTXLZ7TV7EDMEHLXH6LIRANCNFSM6AAAAAAYMSXVZM>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> <learn-academy-2023-delta/week-2-assessment-Phalco1/pull/1/review/1444170331
>> @github.com>
>>
>

2023-05-26 22:57 UTC, chrisyhlee approved these changes
Thanks for making the changes, and good work on this assessment! I left comments throughout for you to look at, if you have any further questions please let me know! I suggest you focus on elaborating more in your interview questions in order to fully convey the extent of your knowledge to the interviewer. Your pseudo code is doing a good job in covering each step, and you have a solid basic understanding of these concepts so far. This assessment currently displays Novice, but you are very close to Advanced Beginner, solid work!

2023-05-26 22:57 UTC, chrisyhlee commented on code-challenges.test.js
> +    let theVowel = []
no need for this variable!

2023-05-26 23:05 UTC, merged

2023-05-29 02:01 UTC, Phalco1 commented
Thanks a lot for the feedback.

On Fri, May 26, 2023 at 17:57 Chris ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Thanks for making the changes, and good work on this assessment! I left
> comments throughout for you to look at, if you have any further questions
> please let me know! I suggest you focus on elaborating more in your
> interview questions in order to fully convey the extent of your knowledge
> to the interviewer. Your pseudo code is doing a good job in covering each
> step, and you have a solid basic understanding of these concepts so far.
> This assessment currently displays Novice, but you are very close to
> Advanced Beginner, solid work!
> ------------------------------
>
> In code-challenges.test.js
> <https://github.com/learn-academy-2023-delta/week-2-assessment-Phalco1/pull/1#discussion_r1207452636>
> :
>
> >  // Pseudo code:
> +
> +// 1.) Write a function that will iterate over the strings its index. Set the parameter, used the word "string" as a placeholder.
> +
> +// 2.) In the block of code you want the iteration to read the index, and if it identifies a vowel in the word, it will stop the iteration.
> +//     Im going to use a for loop to make this iteration to go through the string and identify the values that i set in the array(vowels)
> +
> +// 3.) Create a conditional "if" statement that states: if any values in the array are identified, the .includes() method will return the value that is true(vowels).
> +
> +// 4.) Return the index as is, which will be the index where the value(vowels) in the array is identified.
> +
> +
> +const vowels =["a", "e", "i", "o", "u"]
> +
> +const firstVowel = (string) => {
> +    let theVowel = []
>
> no need for this variable!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/learn-academy-2023-delta/week-2-assessment-Phalco1/pull/1#pullrequestreview-1447036714>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A65Q3ZAAHKA3TLOGH6Z23OTXIEYNDANCNFSM6AAAAAAYMSXVZM>
> .
> You are receiving this because you authored the thread.Message ID:
> <learn-academy-2023-delta/week-2-assessment-Phalco1/pull/1/review/1447036714
> @github.com>
>